### ISSUE TITLE
Holes inside the models

### ISSUE THREAD

**Issue by binaryzebra** [sp4cerat/Fast-Quadric-Mesh-Simplification#11]
Hello, 

I am trying to use your algorithm in my experiments, but as a result, I get holes inside my mesh. Could you please clarify how the model should be prepared to avoid holes after simplification? 

I assume in my model there are many points that have identical or close coordinates but have different uvs, or normals. Does you algorithm handle such cases? 

Best regards,

**Comment by sp4cerat** [comment]
can you upload a test mesh  ? then i may be able to tell

**Comment by binaryzebra** [comment]
[sphere.obj.zip](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/files/2407548/sphere.obj.zip)
[sphere_out.obj.zip](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/files/2407550/sphere_out.obj.zip)

This is simple ICO sphere i can see bugs on. I have another model more complex. I can send it to you in private.

**Comment by binaryzebra** [comment]
duplicates are because of normals  tangents and binormals and uvs. I fastly exported that to give the model. So technically it's different vertices. 

What would you recommend to do with such models when positions are the same, but vertices are technically different.

**Comment by binaryzebra** [comment]
Am I understand correctly that if I will put uvs, and normals, algorithm will manage such models better?

**Comment by sp4cerat** [comment]
well you can store uvs, normals and tangents per triangle (3 per triangle) and remove duplicate vertices. the reduction will in any case reduce the quality of the uvs and normals however as uv and material seams are not considered when reducing the triangles. to get a good quality, you would need to reduce the mesh by removing duplicate vertices first, then generate a uv layout, then transfer the normal and texture data to the lores meshs normal map and texture map.

**Comment by binaryzebra** [comment]
Thanks for the help and fast response. 

Am I understand correclty that I can extend 
void update_uvs(int i0, const Vertex& v, const vec3f& p, std::vector<int>& deleted)
 To handle 3 normals per triangle in the same way how you handle uvs. Do you think same inteprolation strategy will work for normals? 

Also I think I can drop targents, and rebuild tangent space after simplification. If uvs will be good and normals will be good, I can rebuild tangent & binormal later.

**Comment by sp4cerat** [comment]
>>I can understand that. I believe most important is to keep the hope that it will become better in the future. Also wish you to recover soon!

yes

>>Also I think I can drop targents, and rebuild tangent space after simplification. If uvs will be good and normals will be good, I can rebuild tangent & binormal later.

thats something you need to check if these are good

**Comment by binaryzebra** [comment]
Thanks.
