### ISSUE TITLE
Border problems

### ISSUE THREAD

**Issue by matfrem** [sp4cerat/Fast-Quadric-Mesh-Simplification#14]
I use this to fox some ground meshes and I need to keep borders clean. So I changed this:

// Border check
//if (v0.border != v1.border)  continue; <= old version, destroys borders
if (v0.border || v1.border)  continue; <== my version, keeps border vertices

Hope this helps.

**Comment by Zylann** [comment]
Are you using this to keep terrain chunk border vertices intact? I'm considering this library for that purpose, but I'd like to be able to configure it so that specific vertices (on the borders) don't get touched.

**Comment by matfrem** [comment]
yes, it works. with the modification i've told.

**Comment by Error1000** [comment]
This also fixes an issue with duplicated triangles where it leaves gaps in the mesh here is an example obj file(stanford dragon), that when processed with the normal program leaves gaps in the mesh even when using lossless simplification:
[dup.zip](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/files/4011094/dup.zip)

:

**Comment by Error1000** [comment]
This also resolves an issue where it would leave gaps in meshes that have duplicate triangles that have the same position data but different texture coordinate data or other data.

**Comment by neurolabusc** [comment]
I believe this issue actually the same as [issue 24](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/issues/24). I believe this is resolved with a recent [pull request](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/pull/26) which initializes borders before the first error metric calculations. Therefore, I am closing this issue. If you feel this does not address this issue, can you re-open the issue and provide an example mesh that demonstrates the problem.
