### ISSUE TITLE
coordinates changed after simplification

### ISSUE THREAD

**Issue by strawberryloveofzl** [sp4cerat/Fast-Quadric-Mesh-Simplification#19]
i get a result as i hoped but when i put my obj and obj simplified into cloudcompare i find the coordinates has changed! 
![image](https://user-images.githubusercontent.com/40606016/90764517-fa869400-e31a-11ea-8322-e88aaa233fb0.png)

**Comment by Bit00009** [comment]
It's disabled by default to speed up workflow you should enable it.

**Comment by neurolabusc** [comment]
Thanks @Bit00009 for resolving this issue.  I am closing this issue based on your solution.

**Comment by strawberryloveofzl** [comment]
VERY THINKS
