### ISSUE TITLE
Shader Error !A bunch of magical questions

### ISSUE THREAD

**Issue by weiyu666** [sp4cerat/Fast-Quadric-Mesh-Simplification#21]
my computer is usually using 430440 version, and I don't know if it is a version or a problem with video card driver hardware?
![图片](https://user-images.githubusercontent.com/22174508/96099453-d784f480-0f05-11eb-8357-e5772a0e8aed.png)

What's more, there's a magic thing about visual studio 2017 / 2019. I want to modify the output directory of exe for convenience. Debug can't modify all the attribute configurations and so on!

**Comment by neurolabusc** [comment]
Unable to replicate.
