### ISSUE TITLE
Holes in simplified mesh

### ISSUE THREAD

**Issue by michaelpolakatwork** [sp4cerat/Fast-Quadric-Mesh-Simplification#23]
![image](https://user-images.githubusercontent.com/8367868/106231693-41c55a80-61c0-11eb-8fcb-00f7d8118c5a.png)

I tried a number of different "aggressiveness" settings to reduce this mesh by 50%.  In every case I ended up with these holes being created.  Is there something I can do to prevent this?  The original mesh is green and the simplified one is red.

**Comment by sp4cerat** [comment]
I would guess that the wing and body are not connected.

**Comment by neurolabusc** [comment]
I am closing this issue. This may be related to the resolved [issue 24](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/issues/24). If you wish to re-open this issue, please provide access to a mesh which demonstrates the issue. It is hard to resolve a problem if we can not replicate the issue.
