### ISSUE TITLE
Strange pits and bumps in certain meshes

### ISSUE THREAD

**Issue by Maeyanie** [sp4cerat/Fast-Quadric-Mesh-Simplification#24]
I have noticed running a simplification over certain meshes (but not all) creates strange one-vertex pits and bumps, even in lossless mode. On the left is the original, on the right is the result of "simplify.exe face.obj face-out.obj 0.9" (using the simplify.exe from your bin.Windows directory to make sure it wasn't my code's fault).
![image](https://user-images.githubusercontent.com/206142/128965113-ba2b3f98-3e4d-4553-9ed7-de175da3d5a3.png)

The fun part is... it's much more prone to happening on Windows than Linux, even with the same file and settings. It also seems to be worse with a 64-bit compile than 32-bit.
There's no difference if it's compiled with GCC or Visual Studio, or if compiler optimizations are on or off.
Changing Simplify.h's internal types from "double" to "float" caused far more of them to appear, changing them to "long double" reduced the number significantly, however the size of them didn't change.

Here is the file used in that test: [face.zip](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/files/6965750/face.zip)
(Originally from https://www.thingiverse.com/thing:4824024 but it has been slightly modified for the purpose of this bug.)

**Comment by neurolabusc** [comment]
As I recall, Windows 64-bit defaults to 64-bit `double` (SSE compatible) precision for floating point calculations, while Windows 32-bit and Linux default to 80-bit `long double` (fpu compatible) precision. So for Linux, defining a value as `double` may make a variable take 64-bits, but the rounding errors for calculations may be done at 80-bits. The wiki for [ long double](https://en.wikipedia.org/wiki/Long_double) notes `An exception is Microsoft Visual C++ for x86, which makes long double a synonym for double`.

These [notes](https://randomascii.wordpress.com/2012/03/21/intermediate-floating-point-precision/) sound relevant.

I wonder if [/fp](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/e7s85ffb(v=vs.90)?redirectedfrom=MSDN) switch makes a difference

**Comment by Maeyanie** [comment]
> I wonder if [/fp](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/e7s85ffb(v=vs.90)?redirectedfrom=MSDN) switch makes a difference

It didn't, but it was worth trying. All of /fp:precise, /fp:strict, and /fp:fast gave an identical result.

**Comment by neurolabusc** [comment]
@Maeyanie I have submitted a pull request that addresses this issue. You can [test the example from my repository](https://github.com/neurolabusc/Fast-Quadric-Mesh-Simplification). For a Unix computer, you can test as follows:

```
g++ Main.cpp -O3 -o simplify
./simplify ~/face.obj ~/xface.obj 0.8 3
```
