### ISSUE TITLE
question of interpolate/barycenter

### ISSUE THREAD

**Issue by fanvanzh** [sp4cerat/Fast-Quadric-Mesh-Simplification#25]
I have a problem with the barycenter interpolation code:
Are points P,A,B,C coplanar?

According to the QEM algorithm, the new point P may not be coplanar with ABC,
so the interpolation equation P = a + u(b-a) + v(c-a) really works?

**Comment by neurolabusc** [comment]
This is a high performance algorithm that makes some tradeoffs for speed. It is ideal for on-the-fly solutions, but you may want to consider slower and more precise methods for other situations. It is worth noting that MeshLab includes a few alternatives.
