### ISSUE TITLE
Question: It it possible for it to optimise hollow cylinder geometry without breaking it?

### ISSUE THREAD

**Issue by VegarRingdalAibel** [sp4cerat/Fast-Quadric-Mesh-Simplification#28]
It it possible for it to optimise cylinder geometry without breaking it?
Maybe this just isnt possible..

Tried this one with a stl file
https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/

Was hoping it would be able to improve it without breaking it, but might need
![image](https://user-images.githubusercontent.com/94840334/175526609-14ddab8a-2640-4f36-929e-c5f067419213.png)

Added file I used on the web page
[stl file.zip](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/files/8975821/stl.file.zip)

**Comment by VegarRingdalAibel** [comment]
Or maybe a option to make it skip geometry if its a shape if it will break it ?

**Comment by vegarringdal** [comment]
It it possible for it to check if geometry have 1 or more borders, and not destroy them, that might be a fix for this issue?

**Comment by neurolabusc** [comment]
Each triangle of your cylinder has a border edge. I wonder if a simple fix would be to change [line 489](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/blob/2927c8209be291088b939cd934f1b69844922f26/src.cmd/Simplify.h#L489) from

```
if(v0.border != v1.border)  continue;
```
to
```
if(v0.border || v1.border)  continue;
```

**Comment by neurolabusc** [comment]
It is worth noting that many mesh simplification routines [assume a manifold surface](https://www.alecjacobson.com/weblog/?tag=mesh-decimation).

**Comment by vegarringdal** [comment]
@neurolabusc 

Would that change break anything else ? 
Not at a computer I can edit/test it out atm.

Was hoping this would work with geometry like this since it was working really nicely without breaking anything until I got to stuff with more than one border. 


Btw, thanks taking the time to answer 👍
