### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by jjpark7** [sp4cerat/Fast-Quadric-Mesh-Simplification#3]
Hi, I would like to embed this into my system, instead of putting obj files to it in command line or GUI. Could you give instructions how to compile and run this code, perhaps using makefile?

-- Never mind, I didn't expect compiling it would be this simple that you don't even need a Makefile! Good work!

**Comment by MrSaints** [comment]
If anyone is interested: `g++ -o simplify Main.cpp` (inside `src.cmd`)
