### ISSUE TITLE
raise error when load_obj()

### ISSUE THREAD

**Issue by STILLMOREzzz** [sp4cerat/Fast-Quadric-Mesh-Simplification#30]
0xC0000005: Access violation while reading location 0x00000000. is the detail.
The model has 147889 vertices and 28111 faces, and I set the process_uv is true when using load_obj().
How to solve this problem?

**Comment by STILLMOREzzz** [comment]
The wrong place is "triangles[i].uvs[j] = uvs[uvMap[i][j]];"

**Comment by neurolabusc** [comment]
Unable to replicate. Closing the issue. If you can provide an explicit example that elicits this issue, please re-open.
