### ISSUE TITLE
is it possible to convert format files .mesh in .mesh?

### ISSUE THREAD

**Issue by JunSourceX** [sp4cerat/Fast-Quadric-Mesh-Simplification#33]
is it possible to convert format files .mesh in .mesh?

**Comment by neurolabusc** [comment]
This repository only supports the [OBJ format of meshes](https://en.wikipedia.org/wiki/Wavefront_.obj_file). The minimal style of this allows the code to be inserted into larger projects that support more formats. Therefore, supporting multiple mesh formats is out of scope for this repository.

Many implementations of this algorithm. The [NiiVue live demo](https://niivue.github.io/niivue-mesh/) provides drag and drop support for many neuroimaging formats including [GIfTI](https://www.nitrc.org/projects/gifti/), [ASC](http://www.grahamwideman.com/gw/brain/fs/surfacefileformats.htm), [BYU/GEO/G](http://www.grahamwideman.com/gw/brain/fs/surfacefileformats.htm), [BrainSuite DFS](http://brainsuite.org/formats/dfs/), [ICO/TRI](http://www.grahamwideman.com/gw/brain/fs/surfacefileformats.htm), [PLY](https://en.wikipedia.org/wiki/PLY_(file_format)), [BrainNet NV](https://www.nitrc.org/projects/bnv/), [BrainVoyager SRF](https://support.brainvoyager.com/brainvoyager/automation-development/84-file-formats/344-users-guide-2-3-the-format-of-srf-files), [FreeSurfer](http://www.grahamwideman.com/gw/brain/fs/surfacefileformats.htm), [MZ3](https://github.com/neurolabusc/surf-ice/tree/master/mz3), [OFF](https://en.wikipedia.org/wiki/OFF_(file_format)), [Wavefront OBJ](https://brainder.org/tag/obj/), [STL](https://medium.com/3d-printing-stories/why-stl-format-is-bad-fea9ecf5e45), [Legacy VTK](https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf), [X3D](https://3dprint.nih.gov/). Likewise, the [ThreeJS live demo](https://neurolabusc.github.io/simplifyjs/) could allow a developer to take advantage of the huge number of ThreeJS file loaders. [Surfice](https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage) is a desktop application that uses this method and supports many formats.
