### ISSUE TITLE
Preserving mesh edges (with angle threshold) ?

### ISSUE THREAD

**Issue by yvanblanchard** [sp4cerat/Fast-Quadric-Mesh-Simplification#38]
Hello ,

I notice that edges features of original mesh are not preserved.
Would be important to include a kind of angle threshold to preserve edges (when adjacent triangles sharing edges to be kept have normal vectors with angle below tolerance angle).
See example here : #37

**Comment by neurolabusc** [comment]
The method does try to preserve borders. One can use the aggressiveness
setting to trade off quality versus speed. Simple modifications such as [Tim Knip's option to recompute errors with each iteration](https://github.com/timknip/mesh-decimate/blob/afe533902282612da19ec51767a595f070b1ddc8/src/simplify.js#L12) can also further enhance quality for speed. In general, this method is very fast, but it does make sacrifices for this speed. It can in some situations generate self-intersecting triangles.

I am still not sure you have provided a clear example where the current method performs poorly. Feel free to re-open an issue if you have an explicit examples others can replicate.
