### ISSUE TITLE
Why endless loop on error?

### ISSUE THREAD

**Issue by A9G-Data-Droid** [sp4cerat/Fast-Quadric-Mesh-Simplification#39]
I hit one of these `while(1);` the first time I was testing this. The application continues to consume CPU which makes it look like it is working. The only way to know that it is hung is to read the source.

There are 8 places where an error results in an endless loop. Why doesn't the code end on error?

**Comment by neurolabusc** [comment]
Can you provide a sample mesh that elicits this behavior?

**Comment by A9G-Data-Droid** [comment]
I believe I passed invalid input. The cause is not important. Aren't these endless loops that would cause the program to hang?

https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/blob/2927c8209be291088b939cd934f1b69844922f26/src.cmd/Simplify.h#L940

https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/blob/2927c8209be291088b939cd934f1b69844922f26/src.gl/OBJ.h#L470

https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/blob/2927c8209be291088b939cd934f1b69844922f26/src.gl/glsl.h#L100

https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/blob/2927c8209be291088b939cd934f1b69844922f26/src.gl/Bmp.cpp#L542

**Comment by neurolabusc** [comment]
Each of those occurs after a terminal error is reported with the input data. While I would have written `exit(0);` instead of `while(1)`, it does suggest that your input data is not valid.

**Comment by A9G-Data-Droid** [comment]
Yes, that is what I am saying. It should exit on fatal.
