### ISSUE TITLE
Is this code working? I get only a few triangles as output (screenshot)

### ISSUE THREAD

**Issue by r03ert0** [sp4cerat/Fast-Quadric-Mesh-Simplification#6]
I am using THREE r86, running on Chrome, on a Mac.

<img width="916" alt="screen shot 2018-02-17 at 13 46 52" src="https://user-images.githubusercontent.com/2310732/36341088-256cba7c-13e9-11e8-9acc-3bc79e7fae96.png">

If I use the `SimplifyModifier` from THREE, I do get the knot, but it takes much longer.

**Comment by r03ert0** [comment]
I found that the code is removing much more than the 50% of the triangles that it was supposed to remove (at the end, there's only a couple of hundred triangles). However, if I simplify from the original ~130k triangles to 13k triangles, there are still many holes in the mesh.

**Comment by sp4cerat** [comment]
It appears that you have duplicated vertices. Make sure to merge them first

**Comment by neurolabusc** [comment]
Can you share your model? I was not able to replicate your issue conducting a 95% reduction of this [model](https://raw.githubusercontent.com/ttsiodras/renderer/master/3D-Objects/knot.ply), albeit using my fork of this algorithm that attempts to remove duplicated vertices prior to face reduction.

![knot1](https://user-images.githubusercontent.com/8930807/36341647-79d5de42-13bf-11e8-9b3e-a32e4e894be0.jpg)

**Comment by r03ert0** [comment]
I was just using the default model called in the code. I’ll check for duplicate vertices.

**Comment by r03ert0** [comment]
@neurolabusc: are you using the javascript version of the code? In your github account I only see a Pascal vesion

**Comment by r03ert0** [comment]
oops sorry! wrong repo
(this is the implementation that’s giving me problems: https://gist.github.com/zz85/a317597912d68cf046558006d7647381)

**Comment by neurolabusc** [comment]
@r03ert0 would you mind [exporting](https://github.com/Doodle3D/ThreeJS-export-OBJ) this mesh as a OBJ format file and sharing? It would be a nice test case, but I am not familiar with javascript. However, I think my Pascal [UnifyVertices() function](https://github.com/neurolabusc/Fast-Quadric-Mesh-Simplification-Pascal-/blob/master/mergevertices.pas) is similar to the ThreeJS [Geometry.mergeVertices() function](https://stackoverflow.com/questions/46267844/removing-duplicate-vertices-from-three-js-geometry).

**Comment by r03ert0** [comment]
Here's the torus knot mesh converted to obj format.

[torusKnot.obj.zip](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/files/1733775/torusKnot.obj.zip)

**Comment by r03ert0** [comment]
a bit skinnier
[torusknot2.obj.zip](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/files/1733779/torusknot2.obj.zip)

**Comment by sp4cerat** [comment]
Worked here 

![clipboard01](https://user-images.githubusercontent.com/12142588/36614914-9a375142-18de-11e8-85d3-54937e13be09.jpg)
